Kaizen/Models/ErrorViewModel.cs
using System;

namespace Kaizen.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Kaizen/Models/ISeasonRepository.cs
using System.Collections.Generic;

namespace Kaizen.Models
{
    public interface ISeasonRepository
    {

        IEnumerable<Season> GetAllSeasons { get; }

    }
}

Kaizen/Models/ITeaRepository.cs
using System.Collections;
using System.Collections.Generic;

namespace Kaizen.Models
{
    public interface ITeaRepository
    {
        // IEnumerable<Tea>GetAll

        IEnumerable<Tea> GetAllTeas { get; }
        //IEnumerable<Tea> GetTeasOnSale { get; }

        //how-->ID

        Tea GetTeasById(int teaId);



    }// end
}

Kaizen/Models/Season.cs
using System.Collections.Generic;

namespace Kaizen.Models
{
    public class Season
    {
        public int SeasonId { get; set; }
        public string farmerName { get; set; }
        public string farmerEmail { get; set; }
        public string farmerPhoneNumber { get; set; }
        
        public List<Tea> Teas { get; set; }

    }
}

Kaizen/Models/SeasonRepository.cs
using Kaizen.Data;
using System;
using System.Collections.Generic;

namespace Kaizen.Models
{
    public class SeasonRepository:ISeasonRepository
    {
        //  private readonly Data.ApplicationDbContext _appDbcontext;

        //constructor cactor

        //    public SeasonRepository(ApplicationDbContext appDbcontext)
        //      {
        //           _appDbcontext = appDbcontext;
        //        }

        //   public IEnumerable<Season> GetAllSeasons => _appDbcontext.Seasons;


        IEnumerable<Season> ISeasonRepository.GetAllSeasons => new List<Season>
         {
          new Season{SeasonId=0,farmerName = "Jhon", farmerEmail = "jhon@gmail.com", farmerPhoneNumber = "1234567890"},
         new Season{SeasonId=2, farmerName = "tyreece", farmerEmail = "Tyreece@gmail.com", farmerPhoneNumber = "1234567899"},
        new Season{SeasonId=3, farmerName = "Hella", farmerEmail = "Hella@gmail.com", farmerPhoneNumber = "1234567888" }
        
         };
    }// end
}

Kaizen/Models/Tea.cs
namespace Kaizen.Models
{
    public class Tea
    {
        public int TeaId { get; set; }
        public string TeaName { get; set;}
        public string TeaDescription { get; set;}

        public decimal Price { get; set;}
        public int Tea_Stock { get; set;}
        public string pic { get; set; }

        public int Seasonid { get; set;}
        public Season Season { get; set;}
    }// end 
}

Kaizen/Models/TeaRepository.cs
using Kaizen.Data;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;

namespace Kaizen.Models
{
    public class TeaRepository : ITeaRepository
    {

        //private readonly Data.ApplicationDbContext _appDbContext;

        //public TeaRepository(ApplicationDbContext appdbContext)
        //{
        //    _appDbContext = appdbContext;
        //}

        //public IEnumerable<Tea> GetAllTeas
        //{
        //    get
        //    {
        //        return _appDbContext.Teas.Include(s => s.Season);
        //    }

        //}// end get all sweets

        //public Tea GetTeasById(int teaid) 
        //{
        //return _appDbContext.Teas.FirstOrDefault(s => s.TeaId == teaid);
        //}


        private readonly ISeasonRepository _seasonRepository = new SeasonRepository();

        public IEnumerable<Tea> GetAllTeas => new List<Tea>
                 {//populating the Ienumerable

                     new Tea{TeaId=0,TeaName="Sencha",TeaDescription="greenTea",Price=50.99M,
                              pic="https://www.itoen-global.com/allabout_greentea/img/varieties_lineup01.png",
                     Season=_seasonRepository.GetAllSeasons.ToList()[0],Seasonid=0,Tea_Stock=15 },

                     new Tea{TeaId=1,TeaName="Fukamushi Sencha",TeaDescription="greenTea",Price=55.99M,
                         pic="~/images/sencha.png",
                     Season=_seasonRepository.GetAllSeasons.ToList()[0],Seasonid=0,Tea_Stock=10 },

                     new Tea{TeaId=2,TeaName="Gyokuro",TeaDescription="greenTea",Price=60.99M,
                              pic="~/images/sencha.png",
                     Season=_seasonRepository.GetAllSeasons.ToList()[2],Seasonid=2,Tea_Stock=10 },

                 };

        // public IEnumerable<Sweet> Sweets => throw new NotImplementedException();//*********************




        public Tea GetTeasById(int teaId)
        {
            return GetAllTeas.FirstOrDefault(c => c.TeaId == teaId);
        }//end get id for sweet8
    }
}

Kaizen/Models/info.cs
namespace Kaizen.Models
{
    public class info
    {
        public string name;


    }
}

Kaizen/ViewModels/TeaListViewModel.cs
using Kaizen.Models;
using System.Collections.Generic;
using System.Text.RegularExpressions;

namespace Kaizen.ViewModels
{
    public class TeaListViewModel
    {
        // fetch all Teas
        //current Season
        public IEnumerable<Tea> Teas { get; set; }

        public string CurrentSeason { get; set; }

    }//end
}

Kaizen/Controllers/HomeController.cs
using Kaizen.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Kaizen.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public IActionResult takename(string name)
        {
            return View();
        
        }

    }
}

Kaizen/Controllers/SeasonController.cs
using Kaizen.Models;
using Microsoft.AspNetCore.Mvc;

namespace Kaizen.Controllers
{
    public class SeasonController : Controller
    {
        

         private readonly ISeasonRepository _seasonRepository;
         private readonly ITeaRepository _teaRepository;

        public SeasonController(ISeasonRepository seasonRepository, ITeaRepository teaRepository)
        {
            _seasonRepository = seasonRepository;
            _teaRepository = teaRepository;
        }


        public ViewResult List2()
        { // we want to view the sweets
            return View(_seasonRepository.GetAllSeasons);
        }


    }// end class


}

Kaizen/Controllers/TeasController.cs
using Kaizen.Models;
using Kaizen.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace Kaizen.Controllers
{
    public class TeasController : Controller
    {
        //  public IActionResult Index()
        // {
        //     return View();
        //}

        private readonly ISeasonRepository _seasonRepository;
        private readonly ITeaRepository _teaRepository;

        public TeasController(ISeasonRepository seasonRepository, ITeaRepository teaRepository)
        { 
            _teaRepository = teaRepository;
            _seasonRepository = seasonRepository;
        }// end constructor


        public ViewResult List()
        { // we want to view the teas from the repository

            // we now want it to consume the listviewmodel -->.metcore
             return View(_teaRepository.GetAllTeas);
            //  var teaListViewModel= new TeaListViewModel();
            // teaListViewModel.Teas = _teaRepository.GetAllTeas;
            //teaListViewModel.CurrentSeason = "tester";
            //return View(teaListViewModel);


        }// end list 

        public IActionResult Details(int id)
        {
            var tea = _teaRepository.GetTeasById(id);
            if (tea == null) return NotFound();
            return View(tea);
        }// end iAction






    }// end 
}

Kaizen/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<html >
<body style="background-color:#B6BB85;">
    <img alt="Girl in a jacket" style="width:1100px;height:203px;" src="~/images/green 1.jpg" />


<div class="text-center">
        <h1 class="display-4" style="color:antiquewhite;">Welcome </h1>
        <p style="color: antiquewhite;">Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

    <form asp-action="takename" method="post">
    

    <input type="text" id="name" name="name">
    <button type="submit" onclick="alert(name)">Click Me!</button>


    </form>
   </body>
</html>

Kaizen/Views/Season/List2.cshtml
@model IEnumerable<Kaizen.Models.Season>

<style>

    table, th, td {
        border: 1px solid  blue;
        border-collapse: collapse;
        border-radius: 10px;
    }

    th, td {
        background-color: yellowgreen;
    }


</style>

<html>

<head>

    <meta charset="utf-8" />
    <meta hhtp-equiv="X-UA-Compatible" content="IE-edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title> shoppe- sweets pty ltd - 2023</title>

</head>
<body>

    <h1>seasons for teas </h1>
    <table class="table">
        <tr>
            <th style="text-align:center;">farmer name</th>
            <th style="text-align:center;">farmer email</th>
            <th style="text-align:center;">farmer phone number </th>
            <th></th>
        </tr>
    @foreach (var season in Model)
    {
            <tr>
                <th>
                  @season.farmerName
                </th>
                <th>
                   @season.farmerEmail
                </th>
                <th>
                   @season.farmerPhoneNumber
                </th>
                <td>

                    <a fdprocessedid="ite2ji" asp-action="Delete" asp-route-id="@season.SeasonId">Delete</a>
                    @*<button type="button" class="btn btn-link" fdprocessedid="ite2ji" asp-action="Edit" asp-route-id="@season.SeasonId"> Edit</button>*@
                    @*<button type="button" class="btn btn-link" fdprocessedid="ite2ji" asp-action="Details" asp-route-id="@season.SeasonId"> Details</button>*@
                    @*<button type="button" class="btn btn-link" fdprocessedid="ite2ji" asp-action="Delete" asp-route-id="@season.SeasonId"> Delete</button>*@
                    <button type="button" class="btn btn-link" fdprocessedid="ite2ji" asp-area="" asp-controller="Teas" asp-action="Details"> Details</button>

                </td>
                
            </tr>
    
    }
    </table>
</body>
</html>

Kaizen/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    
       
        <link rel="icon" type="image/x-icon" href="~/images/tea1.ico">
    
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Kaizen</title>
    @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />*@
    <link rel="stylesheet" href="~/css/mycsstheme.css"/>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body >
    <header style ="background-color:#4F6132">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3" >
            <div class="container" >
                <img src="~/images/logo.png" style="width:60px;height:50px;" />
                <a class="navbar-brand"asp-area="" asp-controller="Home" asp-action="Index"> Kaizen</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">About Us</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Season" asp-action="List2">Seasons</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Teas" asp-action="List">Teas</a>
                        </li>
                        
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Kaizen - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    @*<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>*@
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Kaizen/Views/Teas/Details.cshtml
@*@page
@model classblog2.Views.Sweets.DetailsModel
@{*@

@*@model Tea*@

@*@model IEnumerable<Kaizen.Models.Tea>*@
@*<h1>@</h1>

<div class="thumbnail">
    @*<img alt="@Model.TeaName" src="@Model.ImageUrl" />
    <div class="caption-full">
        <h3 class="pull-right">@Model.Price</h3>
         <h3 class="pull-right">@Model.price</h3>
        <h3><a href="#">@Model.TeaName</a></h3>
        <p>@Model.TeaDescription</p>
    </div>*@



</div>


@*}*@

Kaizen/Views/Teas/List.cshtml
@model IEnumerable<Kaizen.Models.Tea>

    @*@model *@
<html>
<style>
  /*  .card {
        box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
        transition: 0.3s;
        width: 40%;
    }*/

        .card:hover {
            box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);
        flex-direction: column;
        }

    .container {
        padding: 2px 16px;
    }

    .card {
        flex-direction: column;
        box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
        transition: 0.3s;
        border-radius: 5px; /* 5px rounded corners */
        align-content:center

    }

    /* Add rounded corners to the top left and the top right corner of the image */
    img {
        border-radius: 5px 5px 0 0;
    }

    .flip-card {
        flex-direction: column;
        background-color: transparent;
        width: 300px;
        height: 300px;
        border: 1px solid #f1f1f1;
        border-radius: 5px; /* 5px rounded corners */
        perspective: 1000px; /* Remove this if you don't want the 3D effect */
    }

    /* This container is needed to position the front and back side */
    .flip-card-inner {
        flex-direction: column;
        position: relative;
        width: 100%;
        height: 100%;
        text-align: center;
        transition: transform 0.8s;
        transform-style: preserve-3d;
    }

    /* Do an horizontal flip when you move the mouse over the flip box container */
    .flip-card:hover .flip-card-inner {
        transform: rotateY(180deg);
    }

    /* Position the front and back side */
    .flip-card-front, .flip-card-back {
        flex-direction: column;
        position: absolute;
        width: 100%;
        height: 100%;
        -webkit-backface-visibility: hidden; /* Safari */
        backface-visibility: hidden;
    }

    /* Style the front side (fallback if image is missing) */
    .flip-card-front {
        border-radius: 5px; /* 5px rounded corners */
        background-color: #bbb;
        color: black;
    }

    /* Style the back side */
    .flip-card-back {
        border-radius: 5px; /* 5px rounded corners */
        background-color: dodgerblue;
        color: white;
        transform: rotateY(180deg);
    }

     button {
        border: none;
        outline: 0;
        padding: 12px;
        color: white;
        background-color: #000;
        text-align: center;
        cursor: pointer;
        width: 100%;
        font-size: 18px;
    }

        .button:hover {
            opacity: 0.7;
        }
</style>
<head>

        <meta charset="utf-8" />
        <meta hhtp-equiv="X-UA-Compatible" content="IE-edge"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />

        <title> shoppe- sweets pty ltd - 2023</title>

</head>
<body>

   <div><b>sweets from the sweet repository</b><br /></div>
  @*  <table class="table table-bordered table-responsive table-hover">
        <tr>
            <th>name </th>
            <th>description </th>
            <th>price </th>
            <th>category</th>
            <th>Pic</th>

        </tr>

        @foreach (var tea in Model)
        {
            <tr>
                <td><a href="#">@tea.TeaName</a>
            <td>@tea.TeaDescription</td>
            <td>@tea.Tea_Stock</td>
            <td>@tea.Price.ToString("c")</td>
            <td>@tea.Season.SeasonName</td>


            </td>
                <h3>
                    <a asp.asp-controller="Sweets" asp-action="Details"
                   asp-route-id="@tea.TeaId">@tea.TeaName</a>
                </h3>
                
                <p>@tea.TeaDescription</p>
        </tr>
    }
    </table>*@


    <div style="display:flex">
        @foreach(var tea in Model)
            {
                  @* <div class="card">
        <div class="container" >
                <h4><b>@tea.TeaName</b></h4>
                <p>@tea.TeaDescription</p>
            </div>
        </div>*@
       
<div class="flip-card"  >
        <div class="flip-card-inner">
            <div class="flip-card-front">
                    <h4><b>@tea.TeaName</b></h4>
                        @*<img src="@Sweet.ImageUrl" alt="Image for sweet shop" width="160" height="100" />*@
                        <img src="@tea.pic" alt="Avatar" style="width:200px;height:200px;">
    
</div>
                <div class="flip-card-back">

                    <p>@tea.TeaDescription</p>
                        <p>
                            <a asp-controller="Season" asp-action="List2"> yes</a>
                            <button >Update Stock</button></p>
                </div>
        </div>
            </div>
       
        }
    </div>
    
</body>
</html>